name: Build TTF
description: Build TTF
inputs:
  strict:
    default: "nostrict"
    required: false
    description: "Strict or not strict"
  weight:
    default: "0"
    required: false
    description: "Font weight"
  filename-prefix:
    default: "sakamata-font"
    required: false
    description: "Font filename prefix"

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install requirements
      shell: bash
      run: builder/build/_install_reqs_ubuntu.sh

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Run build
      shell: bash
      run: |
        cd builder/build
        dotnet run -- --rawdir ../../raw --weight ${{ inputs.weight }} --${{ inputs.strict }} --filename ${{ inputs.filename-prefix }}-${{ inputs.weight }}-${{ inputs.strict }} --fontname "Sakamata Chloe Font"

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.filename-prefix }}-${{ inputs.weight }}-${{ inputs.strict }}
        path: |
          builder/build/*.ttf
          builder/build/*.sources.tsv

    - name: Upload source bitmap
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.filename-prefix }}-${{ inputs.weight }}-${{ inputs.strict }}-bmp
        path: |
          builder/build/workdir/*.bmp

    - name: Upload source svg
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.filename-prefix }}-${{ inputs.weight }}-${{ inputs.strict }}-svg
        path: |
          builder/build/workdir/*.svg

